### PR TITLE
Look up custom XDG user directories

### PR DESCRIPTION
**Pull request by jpcima**
This implements Linux directory search as discussed in #32.
Implements the same parsing algorithm as Glib

The attached program allows to test the feature.
For example: `sst-xdg-user-dir XDG_DOCUMENTS_DIR`

[sst-xdg-user-dir.cpp.gz](https://github.com/surge-synthesizer/sst-plugininfra/files/9397772/sst-xdg-user-dir.cpp.gz)

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh this is great!

let me merge this and I can update xt for 1.1.1

**Comment by baconpaul** [comment]
Oh we should figure out how to add your test to the catch2 tests also so we can run them forever in ci.

**Comment by jpcima** [comment]
> Oh we should figure out how to add your test to the catch2 tests also so we can run them forever in ci.

Ok I will make this in a follow up PR.
I believe the easiest is to make an auxiliary function that accepts `istream` in its arguments.

**Comment by baconpaul** [comment]
We can also make the tests run consistently in the top of the source directory if you want to stage a file here and set the directory. Lots of options.

I am updating surge now to use this change. Thank you very much! I'm sure lots of people will love it in our point release later this week :)

**Pull request merged**
