### PR TITLE
Allow building for !x86 in general 

### PR DESCRIPTION
**Pull request by falkTX**
We can make use of simde in the same way that arm/neon is used at the moment, and enable RISC-V builds.

An alternative would be to use simde for all architectures when neither i686 or x86_64 is detected, instead of picking individual architectures manually.
I will let you decide which one is best.

### CODE REVIEW

**Comment by baconpaul** [comment]
I don’t know enough about riscv. Does the arm assembly which is activated bu the new is arm neon or riscv work? Is it appropriate that isarm return true for riscv?

i would have thought the answer to both was no.

**Comment by falkTX** [comment]
dont know about the 1st, but 2nd one is no - riscv is not neon.
see https://stackoverflow.com/questions/66559642/any-neon-equivalent-for-risc-v

for now there is no real simd support in risc-v, we have to fake it.

**Comment by baconpaul** [comment]
Right then this diff is wrong, isarm will return true for a riscv right?

i think yu don’t want isarm neon or riskv but instead have two defines, add an isriskv function. Etc

**Comment by baconpaul** [comment]
Or alternately just remove tie is arm altogether since it is vestigial and use the defines we mean

**Comment by falkTX** [comment]
I need to do a similar change in order to build for emscripten/wasm, so I will refresh the patch in the afternoon to support both. maybe something more generic so new architectures (supported by simde) dont fail by default.

**Comment by baconpaul** [comment]
Yeah would happily have a merge which is like needs simde and turns it in then just makes isarm use asrch64 directly. That’s a way better change 

thanks!

**Comment by baconpaul** [comment]
Actually looking here, this is just weird. Your diff is basically correct but ARM_NEON should be ARM_NOT_X86 the way it is written. Let me peek and maybe I'll do a push which changes this.

**Comment by falkTX** [comment]
I forced pushed a cleaner version, please have a look

**Comment by baconpaul** [comment]
Yup great. Thank you.

**Pull request merged**
